### ISSUE TITLE
Sample?

### ISSUE THREAD

**Issue by Nosfert** [Darkhogg/LWJTorrent#1]
Hi
Im looking at your code, im quite new to creating torrent handling with java so i would appreciate if you got any sample code that i could look at?

Im mainly trying to download torrent files.

**Comment by Darkhogg** [comment]
Sadly, this project has been stopped for a while now, and the part of it that was meant to _actually_ download anything is not done yet. Using what is in there, though, you might beable to build something. But I don't think you're looking for that...
